// ─── Pre-loaded Users ────────────────────────────────────────────────────────
export const USERS = [
  { username: 'Gibbs',  email: 'gibbs@pgadraft.com',  role: 'admin' as const },
  { username: 'Ryan',   email: 'ryan@pgadraft.com',   role: 'user'  as const },
  { username: 'Doby',   email: 'doby@pgadraft.com',   role: 'user'  as const },
  { username: 'Kev',    email: 'kev@pgadraft.com',    role: 'user'  as const },
  { username: 'Dief',   email: 'dief@pgadraft.com',   role: 'user'  as const },
  { username: 'Stevie', email: 'stevie@pgadraft.com', role: 'user'  as const },
  { username: 'Geoff',  email: 'geoff@pgadraft.com',  role: 'user'  as const },
  { username: 'Erm',    email: 'erm@pgadraft.com',    role: 'user'  as const },
];

// ─── Tournaments ─────────────────────────────────────────────────────────────
export const TOURNAMENTS = [
  {
    id: 'players-championship',
    name: 'The Players Championship',
    shortName: 'THE PLAYERS',
    year: 2026,
    startDate: 'March 12–15, 2026',
    draftDate: 'March 8, 2026',
    espnEventId: '401811937',
    fieldSize: 123,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 65,
  },
  {
    id: 'masters',
    name: 'The Masters',
    shortName: 'MASTERS',
    year: 2026,
    startDate: 'April 9–12, 2026',
    draftDate: 'April 5, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 4,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 50,
  },
  {
    id: 'pga-championship',
    name: 'PGA Championship',
    shortName: 'PGA CHAMP.',
    year: 2026,
    startDate: 'May 14–17, 2026',
    draftDate: 'May 10, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 70,
  },
  {
    id: 'us-open',
    name: 'U.S. Open',
    shortName: 'U.S. OPEN',
    year: 2026,
    startDate: 'June 18–21, 2026',
    draftDate: 'June 14, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 60,
  },
  {
    id: 'the-open',
    name: 'The Open Championship',
    shortName: 'THE OPEN',
    year: 2026,
    startDate: 'July 16–19, 2026',
    draftDate: 'July 12, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 65,
  },
];

// ─── Scoring ─────────────────────────────────────────────────────────────────
export const TOP_10_POINTS = [-25, -15, -10, -8, -6, -5, -4, -3, -2, -1];
export const SCORING_PLAYERS = 3;
export const PICK_TIMER_SECONDS = 120;

// ─── Static Field Fallbacks ───────────────────────────────────────────────────
// Used when both ESPN and DraftKings APIs fail to return player data.
// These are the confirmed fields for each tournament, scraped from official sources.
// Names are in ESPN display format. No ESPN IDs yet — scoring uses name matching.

export const STATIC_FIELDS: Record<string, string[]> = {
  'players-championship': [
    'Ludvig Aberg', 'Zach Bauchou', 'Daniel Berger', 'Christiaan Bezuidenhout',
    'Akshay Bhatia', 'Keegan Bradley', 'Michael Brennan', 'Jacob Bridgeman',
    'Sam Burns', 'Brian Campbell', 'Patrick Cantlay', 'Ricky Castillo',
    'Bud Cauley', 'Wyndham Clark', 'Eric Cole', 'Corey Conners',
    'Pierceson Coody', 'Joel Dahmen', 'Cam Davis', 'Jason Day',
    'Zecheng Dou', 'Nico Echavarria', 'Harris English', 'A.J. Ewart',
    'Tony Finau', 'Steven Fisk', 'Matt Fitzpatrick', 'Tommy Fleetwood',
    'Rickie Fowler', 'Ryan Fox', 'Ryan Gerard', 'Lucas Glover',
    'Chris Gotterup', 'Max Greyserman', 'Ben Griffin', 'Emiliano Grillo',
    'Harry Hall', 'Brian Harman', 'Russell Henley', 'Garrick Higgo',
    'Joe Highsmith', 'Ryo Hisatsune', 'Lee Hodges', 'Rico Hoey',
    'Tom Hoge', 'Nicolai Hojgaard', 'Rasmus Hojgaard', 'Max Homa',
    'Viktor Hovland', 'Mark Hubbard', 'Mackenzie Hughes', 'Sungjae Im',
    'Stephan Jaeger', 'Takumi Kanaya', 'Johnny Keefer', 'Michael Kim',
    'S.H. Kim', 'Si Woo Kim', 'Chris Kirk', 'Kurt Kitayama',
    'Jake Knapp', 'Brooks Koepka', 'Min Woo Lee', 'Haotong Li',
    'Shane Lowry', 'Robert MacIntyre', 'Hideki Matsuyama', 'Denny McCarthy',
    'Matt McCarty', 'Max McGreevy', 'Rory McIlroy', 'Maverick McNealy',
    'Mac Meissner', 'Keith Mitchell', 'Taylor Moore', 'Collin Morikawa',
    'William Mouw', 'Alex Noren', 'Andrew Novak', 'Thorbjorn Olesen',
    'Matthieu Pavon', 'Taylor Pendrith', 'Marco Penge', 'Chandler Phillips',
    'J.T. Poston', 'Aldrich Potgieter', 'Andrew Putnam', 'Aaron Rai',
    'Chad Ramey', 'Kristoffer Reitan', 'Davis Riley', 'Patrick Rodgers',
    'Justin Rose', 'Kevin Roy', 'Xander Schauffele', 'Scottie Scheffler',
    'Adam Schenk', 'Matti Schmid', 'Adam Scott', 'Alex Smalley',
    'Jordan Smith', 'Austin Smotherman', 'J.J. Spaun', 'Jordan Spieth',
    'Sam Stevens', 'Sepp Straka', 'Nick Taylor', 'Sahith Theegala',
    'Justin Thomas', 'Davis Thompson', 'Michael Thorbjornsen', 'Sami Valimaki',
    'Erik van Rooyen', 'Jhonattan Vegas', 'Karl Vilips', 'Danny Walker',
    'Vince Whaley', 'Gary Woodland', 'Sudarshan Yellamaraju', 'Cameron Young',
    'Kevin Yu',
  ],
};