// ─── Pre-loaded Users ────────────────────────────────────────────────────────
export const USERS = [
  { username: 'Gibbs',  email: 'gibbs@pgadraft.com',  role: 'admin' as const },
  { username: 'Ryan',   email: 'ryan@pgadraft.com',   role: 'user'  as const },
  { username: 'Doby',   email: 'doby@pgadraft.com',   role: 'user'  as const },
  { username: 'Kev',    email: 'kev@pgadraft.com',    role: 'user'  as const },
  { username: 'Dief',   email: 'dief@pgadraft.com',   role: 'user'  as const },
  { username: 'Stevie', email: 'stevie@pgadraft.com', role: 'user'  as const },
  { username: 'Geoff',  email: 'geoff@pgadraft.com',  role: 'user'  as const },
  { username: 'Erm',    email: 'erm@pgadraft.com',    role: 'user'  as const },
];

// ─── Tournaments ─────────────────────────────────────────────────────────────
export const TOURNAMENTS = [
  {
    id: 'players-championship',
    name: 'The Players Championship',
    shortName: 'THE PLAYERS',
    year: 2026,
    startDate: 'March 12–15, 2026',
    draftDate: 'March 8, 2026',
    espnEventId: '401811937',
    fieldSize: 123,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 65,
  },
  {
    id: 'masters',
    name: 'The Masters',
    shortName: 'MASTERS',
    year: 2026,
    startDate: 'April 9–12, 2026',
    draftDate: 'April 5, 2026',
    espnEventId: '401811941',
    fieldSize: 91,
    maxPicks: 4,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 50,
  },
  {
    id: 'pga-championship',
    name: 'PGA Championship',
    shortName: 'PGA CHAMP.',
    year: 2026,
    startDate: 'May 14–17, 2026',
    draftDate: 'May 10, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 70,
  },
  {
    id: 'us-open',
    name: 'U.S. Open',
    shortName: 'U.S. OPEN',
    year: 2026,
    startDate: 'June 18–21, 2026',
    draftDate: 'June 14, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 60,
  },
  {
    id: 'the-open',
    name: 'The Open Championship',
    shortName: 'THE OPEN',
    year: 2026,
    startDate: 'July 16–19, 2026',
    draftDate: 'July 12, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 65,
  },
];

// ─── Scoring ─────────────────────────────────────────────────────────────────
export const TOP_10_POINTS = [-25, -15, -10, -8, -6, -5, -4, -3, -2, -1];
export const SCORING_PLAYERS = 3;
export const PICK_TIMER_SECONDS = 120;

// ─── Tournament timezone offsets (hours from UTC) ─────────────────────────────
// Used for hourly snapshot windows and cron timing.
// US events: EDT = -4 (summer), The Open (UK): BST = +1
export const TOURNAMENT_TZ_OFFSETS: Record<string, number> = {
  'players-championship': -4,  // Sawgrass, FL — EDT
  'masters':              -4,  // Augusta, GA — EDT
  'pga-championship':     -4,  // EDT
  'us-open':              -4,  // EDT
  'the-open':             +1,  // UK — BST
};

// ─── Static Field Fallbacks ───────────────────────────────────────────────────
// Used when both ESPN and DraftKings APIs fail to return player data.
// These are the confirmed fields for each tournament, scraped from official sources.
// Names are in ESPN display format. No ESPN IDs yet — scoring uses name matching.

// ─── Static odds ──────────────────────────────────────────────────────────────
// Pre-loaded DraftKings odds for The Players Championship 2026 (as of March 9).
// Used as instant fallback so draft room always shows real odds even if all
// external APIs are down or rate-limited. Format: [name, americanOdds]
export const STATIC_ODDS: Record<string, [string, number][]> = {
  'masters': [
    ['Scottie Scheffler',      +550],
    ['Jon Rahm',               +950],
    ['Bryson DeChambeau',     +1000],
    ['Rory McIlroy',          +1100],
    ['Ludvig Aberg',          +1500],
    ['Xander Schauffele',     +1600],
    ['Cameron Young',         +2000],
    ['Matt Fitzpatrick',      +2000],
    ['Tommy Fleetwood',       +2200],
    ['Collin Morikawa',       +3000],
    ['Justin Rose',           +3000],
    ['Robert MacIntyre',      +3300],
    ['Patrick Reed',          +3500],
    ['Hideki Matsuyama',      +4000],
    ['Min Woo Lee',           +4000],
    ['Jordan Spieth',         +4500],
    ['Brooks Koepka',         +4500],
    ['Chris Gotterup',        +4500],
    ['Justin Thomas',         +5000],
    ['Shane Lowry',           +5000],
    ['Tony Finau',            +5000],
    ['Viktor Hovland',        +5000],
    ['Sepp Straka',           +6000],
    ['Sungjae Im',            +6000],
    ['Adam Scott',            +6000],
    ['Russell Henley',        +6000],
    ['Patrick Cantlay',       +6500],
    ['Corey Conners',         +7000],
    ['Sahith Theegala',       +7000],
    ['Tom Kim',               +7000],
    ['Taylor Pendrith',       +8000],
    ['Keegan Bradley',        +8000],
    ['Denny McCarthy',        +8000],
    ['Tyrrell Hatton',        +8000],
    ['Brian Harman',          +9000],
    ['Joaquin Niemann',      +10000],
    ['Akshay Bhatia',        +10000],
    ['Will Zalatoris',       +10000],
    ['Cameron Davis',        +10000],
    ['Si Woo Kim',           +10000],
    ['Nicolai Hojgaard',     +12500],
    ['Rasmus Hojgaard',      +12500],
    ['Alex Noren',           +15000],
    ['Aaron Rai',            +15000],
    ['Wyndham Clark',        +15000],
    ['Eric Cole',            +15000],
    ['Lucas Glover',         +15000],
    ['Rickie Fowler',        +20000],
    ['Jason Day',            +20000],
    ['Adam Hadwin',          +20000],
    ['Nick Taylor',          +20000],
  ],
  'players-championship': [
    ['Scottie Scheffler',      -115],
    ['Rory McIlroy',           +700],
    ['Xander Schauffele',     +1000],
    ['Collin Morikawa',       +1200],
    ['Jon Rahm',              +1400],
    ['Ludvig Aberg',          +1400],
    ['Brooks Koepka',         +1600],
    ['Tommy Fleetwood',       +1800],
    ['Viktor Hovland',        +1800],
    ['Justin Thomas',         +2000],
    ['Jordan Spieth',         +2000],
    ['Shane Lowry',           +2200],
    ['Patrick Cantlay',       +2500],
    ['Tony Finau',            +2500],
    ['Sahith Theegala',       +2500],
    ['Cameron Young',         +2800],
    ['Russell Henley',        +2800],
    ['Sungjae Im',            +2800],
    ['Hideki Matsuyama',      +2800],
    ['Sepp Straka',           +3000],
    ['Keegan Bradley',        +3000],
    ['Brian Harman',          +3000],
    ['Min Woo Lee',           +3300],
    ['Adam Scott',            +3500],
    ['Corey Conners',         +3500],
    ['Matt Fitzpatrick',      +3500],
    ['Joaquin Niemann',       +3500],
    ['Tyrrell Hatton',        +3500],
    ['Harris English',        +4000],
    ['Dustin Johnson',        +4000],
    ['Billy Horschel',        +4000],
    ['Brendan Steele',        +4000],
    ['Nick Taylor',           +4500],
    ['Aaron Rai',             +4500],
    ['Taylor Moore',          +4500],
    ['Chris Kirk',            +4500],
    ['Denny McCarthy',        +5000],
    ['Rickie Fowler',         +5000],
    ['Tom Kim',               +5000],
    ['Max Greyserman',        +5000],
    ['Patrick Rodgers',       +5000],
    ['Christiaan Bezuidenhout', +5000],
    ['Maverick McNealy',      +5500],
    ['Rasmus Hojgaard',       +5500],
    ['Nicolai Hojgaard',      +5500],
    ['Taylor Pendrith',       +5500],
    ['Sam Burns',             +6000],
    ['Austin Eckroat',        +6000],
    ['Kurt Kitayama',         +6000],
    ['Cameron Davis',         +6000],
    ['Luke List',             +6500],
    ['Eric Cole',             +6500],
    ['Byeong Hun An',         +7000],
    ['Jason Day',             +7000],
    ['Justin Rose',           +7000],
    ['Wyndham Clark',         +7000],
    ['Adam Hadwin',           +7000],
    ['Davis Thompson',        +7000],
    ['Gary Woodland',         +7500],
    ['Alex Smalley',          +8000],
    ['Jake Knapp',            +8000],
    ['J.J. Spaun',            +8000],
    ['Beau Hossler',          +8000],
    ['Matthew NeSmith',       +8000],
    ['Akshay Bhatia',         +8000],
    ['Lucas Glover',          +8000],
    ['Emiliano Grillo',       +9000],
    ['Keith Mitchell',        +9000],
    ['Andrew Novak',          +9000],
    ['Mark Hubbard',          +9000],
    ['Robby Shelton',         +9000],
    ['Erik van Rooyen',       +9000],
    ['Si Woo Kim',           +10000],
    ['Stephan Jaeger',       +10000],
    ['Jhonattan Vegas',      +10000],
    ['Nick Dunlap',          +10000],
    ['Webb Simpson',         +10000],
    ['Will Zalatoris',       +10000],
    ['Brendon Todd',         +10000],
    ['J.T. Poston',          +10000],
    ['Adam Svensson',        +12500],
    ['David Lipsky',         +12500],
    ['Ben Griffin',          +12500],
    ['Kevin Streelman',      +12500],
    ['Carl Yuan',            +12500],
    ['Chez Reavie',          +12500],
    ['Kevin Yu',             +12500],
    ['Matthieu Pavon',       +12500],
    ['Jordan Smith',         +15000],
    ['Sami Valimaki',        +15000],
    ['Ryan Fox',             +15000],
    ['Chris Gotterup',       +15000],
    ['Karl Vilips',          +15000],
    ['Austin Smotherman',    +15000],
    ['Matti Schmid',         +15000],
    ['Vince Whaley',         +15000],
    ['Sam Stevens',          +17500],
    ['Danny Walker',         +17500],
    ['Michael Thorbjornsen', +17500],
    ['Adam Schenk',          +17500],
    ['Kevin Roy',            +17500],
    ['Alex Noren',           +17500],
    ['Davis Riley',          +17500],
    ['S.H. Kim',             +20000],
    ['Pierceson Coody',      +20000],
    ['Joel Dahmen',          +20000],
    ['Sudarshan Yellamaraju',+20000],
    ['Patrick Fishburn',     +20000],
    ['Ryo Hisatsune',        +20000],
    ['Harry Hall',           +20000],
    ['Doug Ghim',            +20000],
    ['Camilo Villegas',      +20000],
    ['Kevin Chappell',       +25000],
    ['Thomas Detry',         +25000],
    ['Nate Lashley',         +25000],
    ['Ben Martin',           +25000],
  ],
};

export const STATIC_FIELDS: Record<string, string[]> = {
  'players-championship': [
    'Ludvig Aberg', 'Zach Bauchou', 'Daniel Berger', 'Christiaan Bezuidenhout',
    'Akshay Bhatia', 'Keegan Bradley', 'Michael Brennan', 'Jacob Bridgeman',
    'Sam Burns', 'Brian Campbell', 'Patrick Cantlay', 'Ricky Castillo',
    'Bud Cauley', 'Wyndham Clark', 'Eric Cole', 'Corey Conners',
    'Pierceson Coody', 'Joel Dahmen', 'Cam Davis', 'Jason Day',
    'Zecheng Dou', 'Nico Echavarria', 'Harris English', 'A.J. Ewart',
    'Tony Finau', 'Steven Fisk', 'Matt Fitzpatrick', 'Tommy Fleetwood',
    'Rickie Fowler', 'Ryan Fox', 'Ryan Gerard', 'Lucas Glover',
    'Chris Gotterup', 'Max Greyserman', 'Ben Griffin', 'Emiliano Grillo',
    'Harry Hall', 'Brian Harman', 'Russell Henley', 'Garrick Higgo',
    'Joe Highsmith', 'Ryo Hisatsune', 'Lee Hodges', 'Rico Hoey',
    'Tom Hoge', 'Nicolai Hojgaard', 'Rasmus Hojgaard', 'Max Homa',
    'Viktor Hovland', 'Mark Hubbard', 'Mackenzie Hughes', 'Sungjae Im',
    'Stephan Jaeger', 'Takumi Kanaya', 'Johnny Keefer', 'Michael Kim',
    'S.H. Kim', 'Si Woo Kim', 'Chris Kirk', 'Kurt Kitayama',
    'Jake Knapp', 'Brooks Koepka', 'Min Woo Lee', 'Haotong Li',
    'Shane Lowry', 'Robert MacIntyre', 'Hideki Matsuyama', 'Denny McCarthy',
    'Matt McCarty', 'Max McGreevy', 'Rory McIlroy', 'Maverick McNealy',
    'Mac Meissner', 'Keith Mitchell', 'Taylor Moore', 'Collin Morikawa',
    'William Mouw', 'Alex Noren', 'Andrew Novak', 'Thorbjorn Olesen',
    'Matthieu Pavon', 'Taylor Pendrith', 'Marco Penge', 'Chandler Phillips',
    'J.T. Poston', 'Aldrich Potgieter', 'Andrew Putnam', 'Aaron Rai',
    'Chad Ramey', 'Kristoffer Reitan', 'Davis Riley', 'Patrick Rodgers',
    'Justin Rose', 'Kevin Roy', 'Xander Schauffele', 'Scottie Scheffler',
    'Adam Schenk', 'Matti Schmid', 'Adam Scott', 'Alex Smalley',
    'Jordan Smith', 'Austin Smotherman', 'J.J. Spaun', 'Jordan Spieth',
    'Sam Stevens', 'Sepp Straka', 'Nick Taylor', 'Sahith Theegala',
    'Justin Thomas', 'Davis Thompson', 'Michael Thorbjornsen', 'Sami Valimaki',
    'Erik van Rooyen', 'Jhonattan Vegas', 'Karl Vilips', 'Danny Walker',
    'Vince Whaley', 'Gary Woodland', 'Sudarshan Yellamaraju', 'Cameron Young',
    'Kevin Yu',
  ],
};