// ─── Pre-loaded Users ────────────────────────────────────────────────────────
export const USERS = [
  { username: 'Gibbs',  email: 'gibbs@pgadraft.com',  role: 'admin' as const },
  { username: 'Ryan',   email: 'ryan@pgadraft.com',   role: 'user'  as const },
  { username: 'Doby',   email: 'doby@pgadraft.com',   role: 'user'  as const },
  { username: 'Kev',    email: 'kev@pgadraft.com',    role: 'user'  as const },
  { username: 'Dief',   email: 'dief@pgadraft.com',   role: 'user'  as const },
  { username: 'Stevie', email: 'stevie@pgadraft.com', role: 'user'  as const },
  { username: 'Geoff',  email: 'geoff@pgadraft.com',  role: 'user'  as const },
  { username: 'Erm',    email: 'erm@pgadraft.com',    role: 'user'  as const },
];

// ─── Tournaments ─────────────────────────────────────────────────────────────
export const TOURNAMENTS = [
  {
    id: 'players-championship',
    name: 'The Players Championship',
    shortName: 'THE PLAYERS',
    year: 2026,
    startDate: 'March 12–15, 2026',
    draftDate: 'March 8, 2026',
    espnEventId: '401811937',
    fieldSize: 123,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 65,
  },
  {
    id: 'masters',
    name: 'The Masters',
    shortName: 'MASTERS',
    year: 2026,
    startDate: 'April 9–12, 2026',
    draftDate: 'April 5, 2026',
    espnEventId: '401811941',
    fieldSize: 91,
    maxPicks: 4,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 50,
  },
  {
    id: 'pga-championship',
    name: 'PGA Championship',
    shortName: 'PGA CHAMP.',
    year: 2026,
    startDate: 'May 14–17, 2026',
    draftDate: 'May 12, 2026',
    espnEventId: '401811947',
    fieldSize: 156,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 70,
  },
  {
    id: 'us-open',
    name: 'U.S. Open',
    shortName: 'U.S. OPEN',
    year: 2026,
    startDate: 'June 18–21, 2026',
    draftDate: 'June 14, 2026',
    espnEventId: '401811952',
    fieldSize: 156,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 60,
  },
  {
    id: 'the-open',
    name: 'The Open Championship',
    shortName: 'THE OPEN',
    year: 2026,
    startDate: 'July 16–19, 2026',
    draftDate: 'July 12, 2026',
    espnEventId: '',
    fieldSize: 0,
    maxPicks: 5,
    status: 'upcoming' as const,
    draftOrder: [],
    draftComplete: false,
    cutLine: 65,
  },
];

// ─── Scoring ─────────────────────────────────────────────────────────────────
export const TOP_10_POINTS = [-25, -15, -10, -8, -6, -5, -4, -3, -2, -1];
export const SCORING_PLAYERS = 3;
export const PICK_TIMER_SECONDS = 120;
// Sentinel: player exists in picks but hasn't teed off yet — worst possible score
export const UNSTARTED_POINTS = 9999;

// ─── Tournament timezone offsets (hours from UTC) ─────────────────────────────
// Used for hourly snapshot windows and cron timing.
// US events: EDT = -4 (summer), The Open (UK): BST = +1
export const TOURNAMENT_TZ_OFFSETS: Record<string, number> = {
  'players-championship': -4,  // Sawgrass, FL — EDT
  'masters':              -4,  // Augusta, GA — EDT
  'pga-championship':     -4,  // EDT
  'us-open':              -4,  // EDT
  'the-open':             +1,  // UK — BST
};

// ─── Static Field Fallbacks ───────────────────────────────────────────────────
// Used when both ESPN and DraftKings APIs fail to return player data.
// These are the confirmed fields for each tournament, scraped from official sources.
// Names are in ESPN display format. No ESPN IDs yet — scoring uses name matching.

// ─── Static odds ──────────────────────────────────────────────────────────────
// Pre-loaded odds used as instant fallback when external APIs are unavailable.
// Format: [name, toWinAmericanOdds, top10AmericanOdds]
// Source: ESPN betting (espn.com/betting) — verified 2026 Masters field
export const STATIC_ODDS: Record<string, [string, number, number?][]> = {
  'masters': [
    ['Scottie Scheffler',           +485,   -194],
    ['Jon Rahm',                    +910,   -120],
    ['Bryson DeChambeau',          +1075,   +104],
    ['Rory McIlroy',               +1150,   +108],
    ['Ludvig Aberg',               +1650,   +154],
    ['Xander Schauffele',          +1800,   +140],
    ['Tommy Fleetwood',            +2300,   +168],
    ['Cameron Young',              +2300,   +182],
    ['Matt Fitzpatrick',           +2350,   +178],
    ['Hideki Matsuyama',           +2700,   +196],
    ['Collin Morikawa',            +3100,   +215],
    ['Robert MacIntyre',           +3400,   +240],
    ['Min Woo Lee',                +3500,   +245],
    ['Justin Rose',                +3500,   +265],
    ['Brooks Koepka',              +3700,   +290],
    ['Jordan Spieth',              +4200,   +285],
    ['Chris Gotterup',             +4200,   +300],
    ['Patrick Reed',               +4300,   +295],
    ['Viktor Hovland',             +4500,   +310],
    ['Russell Henley',             +4700,   +280],
    ['Si Woo Kim',                 +4900,   +290],
    ['Justin Thomas',              +5300,   +370],
    ['Akshay Bhatia',              +5700,   +355],
    ['Patrick Cantlay',            +5800,   +355],
    ['Adam Scott',                 +6000,   +365],
    ['Jason Day',                  +6700,   +380],
    ['Jake Knapp',                 +6700,   +415],
    ['Shane Lowry',                +6900,   +385],
    ['Sam Burns',                  +7000,   +410],
    ['J.J. Spaun',                 +7200,   +430],
    ['Sepp Straka',                +7400,   +420],
    ['Tyrrell Hatton',             +7600,   +440],
    ['Corey Conners',              +7800,   +435],
    ['Nicolai Hojgaard',           +7800,   +445],
    ['Maverick McNealy',           +8400,   +460],
    ['Jacob Bridgeman',            +8600,   +465],
    ['Kurt Kitayama',              +9800,   +510],
    ['Harris English',            +10000,   +510],
    ['Daniel Berger',             +10500,   +530],
    ['Gary Woodland',             +10500,   +560],
    ['Ben Griffin',               +11000,   +540],
    ['Cameron Smith',             +11000,   +590],
    ['Max Homa',                  +12000,   +650],
    ['Rasmus Hojgaard',           +12500,   +640],
    ['Keegan Bradley',            +13500,   +650],
    ['Marco Penge',               +14000,   +700],
    ['Harry Hall',                +15500,   +720],
    ['Alex Noren',                +16000,   +710],
    ['Ryan Gerard',               +16000,   +720],
    ['Nick Taylor',               +19500,   +800],
    ['Ryan Fox',                  +21000,   +920],
    ['Wyndham Clark',             +21000,  +1000],
    ['Brian Harman',              +22500,   +910],
    ['Michael Kim',               +22500,   +940],
    ['Max Greyserman',            +22500,   +970],
    ['Aaron Rai',                 +23000,   +950],
    ['Kristoffer Reitan',         +23000,   +980],
    ['Sergio Garcia',             +24000,   +980],
    ['Casey Jarvis',              +24000,   +980],
    ['Carlos Ortiz',              +25000,  +1025],
    ['Tom McKibbin',              +26000,  +1025],
    ['Dustin Johnson',            +26000,  +1050],
    ['Matt McCarty',              +30000,  +1125],
    ['Haotong Li',                +30000,  +1150],
    ['Andrew Novak',              +31000,  +1150],
    ['Nico Echavarria',           +34000,  +1250],
    ['Rasmus Neergaard-Petersen', +34000,  +1250],
    ['Aldrich Potgieter',         +39000,  +1475],
    ['Sami Valimaki',             +40000,  +1350],
    ['Johnny Keefer',             +40000,  +1425],
    ['Michael Brennan',           +40000,  +1450],
    ['Bubba Watson',              +55000,  +1750],
    ['Zach Johnson',              +57500,  +1650],
    ['Charl Schwartzel',          +67500,  +1900],
    ['Davis Riley',               +85000,  +2500],
    ['Brian Campbell',           +250000,  +5000],
    ['Danny Willett',            +250000,  +5100],
    ['Mason Howell',             +300000,  +6200],
    ['Ethan Fang',               +300000,  +6400],
    ['Angel Cabrera',            +325000,  +7200],
    ['Pongsapak Laopakdee',      +350000,  +8000],
    ['Naoyuki Kataoka',          +450000,  +9600],
    ['Brandon Holtz',            +500000, +31000],
    ['Vijay Singh',              +500000, +15000],
    ['Fred Couples',             +500000, +16500],
    ['Mike Weir',                +500000, +20000],
    ['Mateo Pulcini',            +500000, +20000],
    ['Jackson Herrington',       +500000, +20000],
    ['Jose Maria Olazabal',      +500000, +29000],
  ],
  'pga-championship': [
    ['Scottie Scheffler',     +480],
    ['Rory McIlroy',          +850],
    ['Cameron Young',        +1200],
    ['Jon Rahm',             +1300],
    ['Xander Schauffele',    +1600],
    ['Bryson DeChambeau',    +2000],
    ['Matt Fitzpatrick',     +2200],
    ['Ludvig Aberg',         +2200],
    ['Tommy Fleetwood',      +2500],
    ['Joaquin Niemann',      +4000],
    ['Justin Thomas',        +4000],
    ['Justin Rose',          +4000],
    ['Collin Morikawa',      +4000],
    ['Brooks Koepka',        +4500],
    ['Patrick Cantlay',      +4500],
    ['Tom Kim',              +4600],
    ['Viktor Hovland',       +5000],
    ['Si Woo Kim',           +5000],
    ['Russell Henley',       +5000],
    ['Tyrrell Hatton',       +5000],
    ['Rickie Fowler',        +5500],
    ['Robert MacIntyre',     +5500],
    ['Sam Burns',            +6000],
    ['Chris Gotterup',       +6000],
    ['Adam Scott',           +6000],
    ['Tony Finau',           +6500],
    ['Patrick Reed',         +6500],
    ['Hideki Matsuyama',     +6500],
    ['Jason Day',            +6500],
    ['Sungjae Im',           +6500],
    ['Nicolai Hojgaard',     +6500],
    ['Max Homa',             +6500],
    ['Min Woo Lee',          +7000],
    ['Jordan Spieth',        +7000],
    ['Sepp Straka',          +7000],
    ['J.J. Spaun',           +7000],
    ['Shane Lowry',          +8000],
    ['Will Zalatoris',       +8000],
    ['Wyndham Clark',        +8000],
    ['Tom Hoge',             +8000],
    ['Akshay Bhatia',        +9200],
    ['Maverick McNealy',     +9200],
    ['Corey Conners',       +10000],
    ['Keegan Bradley',      +10000],
    ['Harris English',      +10000],
    ['Kurt Kitayama',       +10000],
    ['Gary Woodland',       +10000],
    ['Rasmus Hojgaard',     +11000],
    ['Aaron Rai',           +12500],
    ['Alex Noren',          +12500],
    ['Alex Smalley',        +12500],
    ['Sahith Theegala',     +15500],
    ['Nick Taylor',         +17500],
    ['Brian Harman',        +17500],
    ['Daniel Berger',       +17500],
    ['Dustin Johnson',      +22500],
    ['Ryan Fox',            +25000],
    ['Ryo Hisatsune',       +25000],
    ['J.T. Poston',         +27000],
    ['Max Greyserman',      +29000],
    ['Denny McCarthy',      +30000],
    ['Lucas Glover',        +50000],
    ['Brandt Snedeker',     +50000],
    ['Stephan Jaeger',      +50000],
    ['Emiliano Grillo',    +100000],
    ['Michael Block',      +500000],
  ],
  'us-open': [
    // Source: FanDuel/DraftKings pre-tournament odds, week of June 15, 2026
    // Shinnecock Hills rewards ball-strikers; adjusted vs. typical odds accordingly
    ['Scottie Scheffler',        +550],
    ['Rory McIlroy',            +1200],
    ['Jon Rahm',                +1300],
    ['Cameron Young',           +2000],
    ['Tommy Fleetwood',         +2000],
    ['Xander Schauffele',       +2000],
    ['Matt Fitzpatrick',        +2200],   // 2022 US Open champion
    ['Ludvig Aberg',            +2200],
    ['Bryson DeChambeau',       +2500],   // 2024 US Open champion
    ['Brooks Koepka',           +3500],   // 3x US Open champion
    ['Russell Henley',          +3500],
    ['Collin Morikawa',         +4000],
    ['Sam Burns',               +4000],
    ['Justin Rose',             +4000],   // 2013 US Open champion
    ['Tyrrell Hatton',          +4000],
    ['Si Woo Kim',              +4000],
    ['Justin Thomas',           +4000],
    ['Wyndham Clark',           +4000],   // 2023 US Open champion
    ['Chris Gotterup',          +4500],
    ['Patrick Cantlay',         +4500],
    ['Patrick Reed',            +4500],
    ['Viktor Hovland',          +4500],
    ['Hideki Matsuyama',        +5000],
    ['Jordan Spieth',           +5000],   // 2015 US Open champion
    ['Robert MacIntyre',        +5500],
    ['Min Woo Lee',             +5500],
    ['Akshay Bhatia',           +6000],
    ['Max Homa',                +6000],
    ['J.J. Spaun',              +6500],
    ['Aaron Rai',               +6500],
    ['Keegan Bradley',          +7000],
    ['Sungjae Im',              +7500],
    ['Shane Lowry',             +7500],   // 2019 Open champion
    ['Joaquin Niemann',         +8000],
    ['Harris English',          +8000],
    ['Tom Kim',                 +9000],
    ['Adam Scott',              +9500],
    ['Daniel Berger',          +10000],
    ['Brian Harman',           +10000],   // 2023 Open champion
    ['Corey Conners',          +10000],
    ['Rasmus Hojgaard',        +10000],
    ['Nick Taylor',            +11000],
    ['Sahith Theegala',        +11000],
    ['Eric Cole',              +12000],
    ['Nicolai Hojgaard',       +12000],
    ['Max Greyserman',         +12500],
    ['Jason Day',              +12500],
    ['Lucas Glover',           +13000],   // 2009 US Open champion
    ['Sepp Straka',            +13000],
    ['Rickie Fowler',          +14000],
    ['Alex Noren',             +14000],
    ['Tony Finau',             +14000],
    ['Taylor Pendrith',        +15000],
    ['Maverick McNealy',       +15000],
    ['Emiliano Grillo',        +17500],
    ['Austin Eckroat',         +17500],
    ['Harry Hall',             +17500],
    ['Andrew Novak',           +17500],
    ['Patrick Rodgers',        +20000],
    ['Denny McCarthy',         +20000],
    ['J.T. Poston',            +20000],
    ['Ben Griffin',            +20000],
    ['Kurt Kitayama',          +22500],
    ['Sudarshan Yellamaraju',  +22500],
    ['Ryan Fox',               +25000],
    ['Ryo Hisatsune',          +25000],
    ['Lucas Herbert',          +28000],
    ['Alex Fitzpatrick',       +30000],
    ['Peter Uihlein',          +35000],
    ['Graeme McDowell',        +50000],   // 2010 US Open champion, via final qualifying
    ['Tiger Woods',            +60000],
    ['Phil Mickelson',        +125000],
    ['Miles Russell',         +300000],   // 17-year-old amateur
  ],
  'players-championship': [
    ['Scottie Scheffler',      -115],
    ['Rory McIlroy',           +700],
    ['Xander Schauffele',     +1000],
    ['Collin Morikawa',       +1200],
    ['Jon Rahm',              +1400],
    ['Ludvig Aberg',          +1400],
    ['Brooks Koepka',         +1600],
    ['Tommy Fleetwood',       +1800],
    ['Viktor Hovland',        +1800],
    ['Justin Thomas',         +2000],
    ['Jordan Spieth',         +2000],
    ['Shane Lowry',           +2200],
    ['Patrick Cantlay',       +2500],
    ['Tony Finau',            +2500],
    ['Sahith Theegala',       +2500],
    ['Cameron Young',         +2800],
    ['Russell Henley',        +2800],
    ['Sungjae Im',            +2800],
    ['Hideki Matsuyama',      +2800],
    ['Sepp Straka',           +3000],
    ['Keegan Bradley',        +3000],
    ['Brian Harman',          +3000],
    ['Min Woo Lee',           +3300],
    ['Adam Scott',            +3500],
    ['Corey Conners',         +3500],
    ['Matt Fitzpatrick',      +3500],
    ['Joaquin Niemann',       +3500],
    ['Tyrrell Hatton',        +3500],
    ['Harris English',        +4000],
    ['Dustin Johnson',        +4000],
    ['Billy Horschel',        +4000],
    ['Brendan Steele',        +4000],
    ['Nick Taylor',           +4500],
    ['Aaron Rai',             +4500],
    ['Taylor Moore',          +4500],
    ['Chris Kirk',            +4500],
    ['Denny McCarthy',        +5000],
    ['Rickie Fowler',         +5000],
    ['Tom Kim',               +5000],
    ['Max Greyserman',        +5000],
    ['Patrick Rodgers',       +5000],
    ['Christiaan Bezuidenhout', +5000],
    ['Maverick McNealy',      +5500],
    ['Rasmus Hojgaard',       +5500],
    ['Nicolai Hojgaard',      +5500],
    ['Taylor Pendrith',       +5500],
    ['Sam Burns',             +6000],
    ['Austin Eckroat',        +6000],
    ['Kurt Kitayama',         +6000],
    ['Cameron Davis',         +6000],
    ['Luke List',             +6500],
    ['Eric Cole',             +6500],
    ['Byeong Hun An',         +7000],
    ['Jason Day',             +7000],
    ['Justin Rose',           +7000],
    ['Wyndham Clark',         +7000],
    ['Adam Hadwin',           +7000],
    ['Davis Thompson',        +7000],
    ['Gary Woodland',         +7500],
    ['Alex Smalley',          +8000],
    ['Jake Knapp',            +8000],
    ['J.J. Spaun',            +8000],
    ['Beau Hossler',          +8000],
    ['Matthew NeSmith',       +8000],
    ['Akshay Bhatia',         +8000],
    ['Lucas Glover',          +8000],
    ['Emiliano Grillo',       +9000],
    ['Keith Mitchell',        +9000],
    ['Andrew Novak',          +9000],
    ['Mark Hubbard',          +9000],
    ['Robby Shelton',         +9000],
    ['Erik van Rooyen',       +9000],
    ['Si Woo Kim',           +10000],
    ['Stephan Jaeger',       +10000],
    ['Jhonattan Vegas',      +10000],
    ['Nick Dunlap',          +10000],
    ['Webb Simpson',         +10000],
    ['Will Zalatoris',       +10000],
    ['Brendon Todd',         +10000],
    ['J.T. Poston',          +10000],
    ['Adam Svensson',        +12500],
    ['David Lipsky',         +12500],
    ['Ben Griffin',          +12500],
    ['Kevin Streelman',      +12500],
    ['Carl Yuan',            +12500],
    ['Chez Reavie',          +12500],
    ['Kevin Yu',             +12500],
    ['Matthieu Pavon',       +12500],
    ['Jordan Smith',         +15000],
    ['Sami Valimaki',        +15000],
    ['Ryan Fox',             +15000],
    ['Chris Gotterup',       +15000],
    ['Karl Vilips',          +15000],
    ['Austin Smotherman',    +15000],
    ['Matti Schmid',         +15000],
    ['Vince Whaley',         +15000],
    ['Sam Stevens',          +17500],
    ['Danny Walker',         +17500],
    ['Michael Thorbjornsen', +17500],
    ['Adam Schenk',          +17500],
    ['Kevin Roy',            +17500],
    ['Alex Noren',           +17500],
    ['Davis Riley',          +17500],
    ['S.H. Kim',             +20000],
    ['Pierceson Coody',      +20000],
    ['Joel Dahmen',          +20000],
    ['Sudarshan Yellamaraju',+20000],
    ['Patrick Fishburn',     +20000],
    ['Ryo Hisatsune',        +20000],
    ['Harry Hall',           +20000],
    ['Doug Ghim',            +20000],
    ['Camilo Villegas',      +20000],
    ['Kevin Chappell',       +25000],
    ['Thomas Detry',         +25000],
    ['Nate Lashley',         +25000],
    ['Ben Martin',           +25000],
  ],
};

export const STATIC_FIELDS: Record<string, string[]> = {
  'us-open': [
    // Top contenders / OWGR Top 50
    'Scottie Scheffler', 'Rory McIlroy', 'Cameron Young', 'Jon Rahm', 'Tommy Fleetwood',
    'Matt Fitzpatrick', 'Collin Morikawa', 'Justin Rose', 'J.J. Spaun', 'Russell Henley',
    'Chris Gotterup', 'Xander Schauffele', 'Robert MacIntyre', 'Ludvig Aberg', 'Hideki Matsuyama',
    'Viktor Hovland', 'Patrick Cantlay', 'Sungjae Im', 'Min Woo Lee', 'Sam Burns',
    'Justin Thomas', 'Wyndham Clark', 'Sahith Theegala', 'Tyrrell Hatton', 'Shane Lowry',
    'Bryson DeChambeau', 'Kristoffer Reitan', 'Tom Kim', 'Akshay Bhatia', 'Rickie Fowler',
    'Jordan Spieth', 'Nicolai Hojgaard', 'Max Homa', 'Sepp Straka', 'Tony Finau',
    'Adam Scott', 'Keegan Bradley', 'Rasmus Hojgaard', 'Corey Conners', 'Si Woo Kim',
    'Jason Day', 'Nick Taylor', 'Taylor Pendrith', 'Alex Noren', 'Austin Eckroat',
    'Harris English', 'Aaron Rai', 'Davis Thompson',
    // Mid-field / qualifiers
    'Maverick McNealy', 'Denny McCarthy', 'Max Greyserman', 'Nick Dunlap', 'Adam Hadwin',
    'Eric Cole', 'Tom Hoge', 'Will Zalatoris', 'Brian Harman', 'Daniel Berger',
    'Stephan Jaeger', 'Brooks Koepka', 'J.T. Poston', 'Ryo Hisatsune', 'Kurt Kitayama',
    'Alex Smalley', 'Emiliano Grillo', 'Ryan Fox', 'Gary Woodland', 'Lucas Glover',
    'Patrick Reed', 'Joaquin Niemann', 'Jake Knapp', 'Harry Hall', 'Aldrich Potgieter',
    'Nico Echavarria', 'Taylor Moore', 'Seamus Power', 'Brendon Todd', 'Chris Kirk',
    'Ben Griffin', 'Andrew Novak', 'Patrick Rodgers', 'Sudarshan Yellamaraju', 'Karl Vilips',
    'Marco Penge', 'Mackenzie Hughes', 'Matt Wallace', 'Nick Hardy', 'David Skinns',
    'Thriston Lawrence', 'Thomas Detry', 'Adrian Meronk', 'Alex Fitzpatrick',
    'Christiaan Bezuidenhout', 'Justin Suh', 'Bud Cauley', 'Charley Hoffman',
    // LIV Golf qualifiers
    'Cameron Smith', 'Lucas Herbert', 'Peter Uihlein', 'Sebastian Soderberg',
    // Final qualifying / special exemptions
    'Graeme McDowell', 'Caleb Surratt', 'Tiger Woods', 'Phil Mickelson',
    'Miles Russell', 'Jordan Smith', 'Ryan Gerard', 'Ben Taylor',
    'Sam Stevens', 'Byeong Hun An', 'Mark Hubbard', 'Erik van Rooyen',
    'Beau Hossler', 'Matthew NeSmith', 'Davis Riley', 'Wyndham Clark',
    'Keith Mitchell', 'Ricky Castillo', 'Ben Silverman',
  ],
  'pga-championship': [
    // Top contenders
    'Scottie Scheffler', 'Rory McIlroy', 'Cameron Young', 'Jon Rahm', 'Xander Schauffele',
    'Bryson DeChambeau', 'Matt Fitzpatrick', 'Ludvig Aberg', 'Tommy Fleetwood', 'Joaquin Niemann',
    'Justin Thomas', 'Justin Rose', 'Collin Morikawa', 'Brooks Koepka', 'Patrick Cantlay',
    'Viktor Hovland', 'Si Woo Kim', 'Russell Henley', 'Tyrrell Hatton', 'Rickie Fowler',
    'Robert MacIntyre', 'Sam Burns', 'Chris Gotterup', 'Adam Scott', 'Tony Finau',
    'Patrick Reed', 'Hideki Matsuyama', 'Jason Day', 'Sungjae Im', 'Nicolai Hojgaard',
    'Max Homa', 'Min Woo Lee', 'Jordan Spieth', 'Sepp Straka', 'Shane Lowry',
    'Will Zalatoris', 'Wyndham Clark', 'Tom Hoge', 'Akshay Bhatia', 'Keegan Bradley',
    'Harris English', 'Rasmus Hojgaard', 'Aaron Rai', 'Corey Conners', 'Sahith Theegala',
    'Nick Taylor', 'Brian Harman', 'Dustin Johnson', 'Denny McCarthy', 'Brandt Snedeker',
    // Mid-field PGA Tour players
    'Jacob Bridgeman', 'Kurt Kitayama', 'Daniel Berger', 'Ben Griffin', 'Max Greyserman',
    'Chris Kirk', 'Stephan Jaeger', 'Nick Dunlap', 'Ryo Hisatsune', 'Tom Kim',
    'Davis Thompson', 'J.T. Poston', 'Adam Schenk', 'Ryan Fox', 'J.J. Spaun',
    'Eric Cole', 'Byeong Hun An', 'Luke List', 'Austin Eckroat', 'Taylor Pendrith',
    'Maverick McNealy', 'Alex Noren', 'Gary Woodland', 'Keith Mitchell', 'Andrew Novak',
    'Mark Hubbard', 'Erik van Rooyen', 'Beau Hossler', 'Matthew NeSmith', 'Lucas Glover',
    'Emiliano Grillo', 'Robby Shelton', 'Billy Horschel', 'Cameron Davis', 'Davis Riley',
    'Patrick Rodgers', 'Alex Smalley', 'Adam Hadwin', 'Sudarshan Yellamaraju', 'Ryan Gerard',
    'Karl Vilips', 'Marco Penge', 'Harry Hall', 'Aldrich Potgieter', 'Kristoffer Reitan',
    'Nico Echavarria', 'Mackenzie Hughes', 'Taylor Moore', 'Scott Stallings', 'Kevin Yu',
    'Seamus Power', 'Sam Ryder', 'Brendon Todd',
    // LIV Golf players with major exemptions
    'Cameron Smith', 'Sebastian Soderberg',
    // DP World Tour / international qualifiers
    'Thriston Lawrence', 'Thomas Detry', 'Adrian Meronk', 'Alex Fitzpatrick',
    'Christiaan Bezuidenhout', 'Justin Suh', 'Bud Cauley', 'Charley Hoffman',
    'Matt Wallace', 'Nick Hardy', 'Ben Taylor', 'David Skinns',
    // Club professionals (PGA of America Golf Pros — via PGA Professional Championship at Bandon Dunes)
    'Michael Block', 'Jesse Droemer', 'Ryan Vermeer', 'Ben Kern', 'Michael Kartrude',
    'Tyler Collet', 'Zach Haynes', 'Garrett Sapp', 'Austin Hurt', 'Braden Shattuck',
    'Mark Geddes', 'Ben Polland', 'Ryan Lenahan', 'Timothy Wiseman', 'Bryce Fisher',
    'Chris Gabriele', 'Jared Jones', 'Paul McClure',
  ],
  'players-championship': [
    'Ludvig Aberg', 'Zach Bauchou', 'Daniel Berger', 'Christiaan Bezuidenhout',
    'Akshay Bhatia', 'Keegan Bradley', 'Michael Brennan', 'Jacob Bridgeman',
    'Sam Burns', 'Brian Campbell', 'Patrick Cantlay', 'Ricky Castillo',
    'Bud Cauley', 'Wyndham Clark', 'Eric Cole', 'Corey Conners',
    'Pierceson Coody', 'Joel Dahmen', 'Cam Davis', 'Jason Day',
    'Zecheng Dou', 'Nico Echavarria', 'Harris English', 'A.J. Ewart',
    'Tony Finau', 'Steven Fisk', 'Matt Fitzpatrick', 'Tommy Fleetwood',
    'Rickie Fowler', 'Ryan Fox', 'Ryan Gerard', 'Lucas Glover',
    'Chris Gotterup', 'Max Greyserman', 'Ben Griffin', 'Emiliano Grillo',
    'Harry Hall', 'Brian Harman', 'Russell Henley', 'Garrick Higgo',
    'Joe Highsmith', 'Ryo Hisatsune', 'Lee Hodges', 'Rico Hoey',
    'Tom Hoge', 'Nicolai Hojgaard', 'Rasmus Hojgaard', 'Max Homa',
    'Viktor Hovland', 'Mark Hubbard', 'Mackenzie Hughes', 'Sungjae Im',
    'Stephan Jaeger', 'Takumi Kanaya', 'Johnny Keefer', 'Michael Kim',
    'S.H. Kim', 'Si Woo Kim', 'Chris Kirk', 'Kurt Kitayama',
    'Jake Knapp', 'Brooks Koepka', 'Min Woo Lee', 'Haotong Li',
    'Shane Lowry', 'Robert MacIntyre', 'Hideki Matsuyama', 'Denny McCarthy',
    'Matt McCarty', 'Max McGreevy', 'Rory McIlroy', 'Maverick McNealy',
    'Mac Meissner', 'Keith Mitchell', 'Taylor Moore', 'Collin Morikawa',
    'William Mouw', 'Alex Noren', 'Andrew Novak', 'Thorbjorn Olesen',
    'Matthieu Pavon', 'Taylor Pendrith', 'Marco Penge', 'Chandler Phillips',
    'J.T. Poston', 'Aldrich Potgieter', 'Andrew Putnam', 'Aaron Rai',
    'Chad Ramey', 'Kristoffer Reitan', 'Davis Riley', 'Patrick Rodgers',
    'Justin Rose', 'Kevin Roy', 'Xander Schauffele', 'Scottie Scheffler',
    'Adam Schenk', 'Matti Schmid', 'Adam Scott', 'Alex Smalley',
    'Jordan Smith', 'Austin Smotherman', 'J.J. Spaun', 'Jordan Spieth',
    'Sam Stevens', 'Sepp Straka', 'Nick Taylor', 'Sahith Theegala',
    'Justin Thomas', 'Davis Thompson', 'Michael Thorbjornsen', 'Sami Valimaki',
    'Erik van Rooyen', 'Jhonattan Vegas', 'Karl Vilips', 'Danny Walker',
    'Vince Whaley', 'Gary Woodland', 'Sudarshan Yellamaraju', 'Cameron Young',
    'Kevin Yu',
  ],
};

// ─── Static OWGR lookup ───────────────────────────────────────────────────────
// Confirmed top 15 from post-Truist Championship OWGR (week of May 12, 2026).
// LIV player ranks confirmed: Hatton #23, DeChambeau #25, Rahm #31,
// Koepka #129 (rejoined PGA Tour 2026), Niemann #172, Smith #222, Johnson #468.
// Ranks 16-22 and 32-50 are best estimates; ranks 50+ are approximate.
// Used as an immediate fallback before the live OWGR API responds.
export const STATIC_OWGR: Record<string, Record<string, number>> = {
  'us-open': {
    // Estimated OWGR week of June 15, 2026 (post-Canadian Open)
    // Based on May 12 rankings adjusted for ~5 weeks of PGA Tour events
    'Scottie Scheffler': 1,
    'Rory McIlroy': 2,
    'Cameron Young': 3,
    'Matt Fitzpatrick': 4,
    'Collin Morikawa': 5,
    'Tommy Fleetwood': 6,
    'Justin Rose': 7,
    'J.J. Spaun': 8,
    'Russell Henley': 9,
    'Chris Gotterup': 10,
    'Xander Schauffele': 11,
    'Robert MacIntyre': 12,
    'Ludvig Aberg': 13,
    'Hideki Matsuyama': 14,
    'Viktor Hovland': 15,
    'Patrick Cantlay': 16,
    'Sungjae Im': 17,
    'Min Woo Lee': 18,
    'Sam Burns': 19,
    'Justin Thomas': 20,
    'Wyndham Clark': 21,
    'Sahith Theegala': 22,
    'Tyrrell Hatton': 23,
    'Shane Lowry': 24,
    'Bryson DeChambeau': 25,
    'Kristoffer Reitan': 26,
    'Tom Kim': 27,
    'Akshay Bhatia': 28,
    'Rickie Fowler': 29,
    'Jordan Spieth': 30,
    'Jon Rahm': 31,
    'Nicolai Hojgaard': 32,
    'Max Homa': 33,
    'Sepp Straka': 34,
    'Tony Finau': 35,
    'Adam Scott': 36,
    'Keegan Bradley': 37,
    'Rasmus Hojgaard': 38,
    'Corey Conners': 39,
    'Si Woo Kim': 40,
    'Jason Day': 41,
    'Nick Taylor': 42,
    'Taylor Pendrith': 43,
    'Alex Noren': 44,
    'Austin Eckroat': 45,
    'Harris English': 46,
    'Aaron Rai': 47,
    'Davis Thompson': 48,
    'Maverick McNealy': 55,
    'Denny McCarthy': 58,
    'Max Greyserman': 62,
    'Nick Dunlap': 66,
    'Adam Hadwin': 71,
    'Eric Cole': 74,
    'Tom Hoge': 79,
    'Will Zalatoris': 84,
    'Brian Harman': 88,
    'Daniel Berger': 93,
    'Stephan Jaeger': 98,
    'J.T. Poston': 104,
    'Ryo Hisatsune': 109,
    'Kurt Kitayama': 115,
    'Alex Smalley': 120,
    'Emiliano Grillo': 128,
    'Brooks Koepka': 129,
    'Ryan Fox': 134,
    'Gary Woodland': 148,
    'Lucas Glover': 195,
    'Patrick Reed': 210,
    'Joaquin Niemann': 172,
    'Cameron Smith': 222,
    'Lucas Herbert': 245,
    'Graeme McDowell': 480,
    'Tiger Woods': 895,
    'Phil Mickelson': 1200,
  },
  'pga-championship': {
    // Confirmed top 15 (post-Truist Championship, May 12 2026)
    'Scottie Scheffler': 1,
    'Rory McIlroy': 2,
    'Cameron Young': 3,
    'Matt Fitzpatrick': 4,
    'Collin Morikawa': 5,
    'Tommy Fleetwood': 6,
    'Justin Rose': 7,
    'J.J. Spaun': 8,
    'Russell Henley': 9,
    'Chris Gotterup': 10,
    'Xander Schauffele': 11,
    'Robert MacIntyre': 12,
    'Ludvig Aberg': 13,
    'Hideki Matsuyama': 14,
    'Viktor Hovland': 15,
    // Estimated ranks 16-22
    'Patrick Cantlay': 16,
    'Sungjae Im': 17,
    'Min Woo Lee': 18,
    'Sam Burns': 19,
    'Justin Thomas': 20,
    'Wyndham Clark': 21,
    'Sahith Theegala': 22,
    // Confirmed LIV player ranks (post-Masters, April 2026; LIV got OWGR in 2026)
    'Tyrrell Hatton': 23,
    'Shane Lowry': 24,
    'Bryson DeChambeau': 25,
    'Kristoffer Reitan': 26,
    'Tom Kim': 27,
    'Akshay Bhatia': 28,
    'Rickie Fowler': 29,
    'Jordan Spieth': 30,
    'Jon Rahm': 31,
    'Nicolai Hojgaard': 32,
    'Max Homa': 33,
    'Sepp Straka': 34,
    'Tony Finau': 35,
    'Adam Scott': 36,
    'Keegan Bradley': 37,
    'Rasmus Hojgaard': 38,
    'Corey Conners': 39,
    'Si Woo Kim': 40,
    'Jason Day': 41,
    'Nick Taylor': 42,
    'Taylor Pendrith': 43,
    'Alex Noren': 44,
    'Austin Eckroat': 45,
    'Harris English': 46,
    'Aaron Rai': 47,
    'Davis Thompson': 48,
    // Approximate ranks 49-200
    'Maverick McNealy': 55,
    'Denny McCarthy': 58,
    'Max Greyserman': 62,
    'Nick Dunlap': 66,
    'Adam Hadwin': 71,
    'Eric Cole': 74,
    'Tom Hoge': 79,
    'Will Zalatoris': 84,
    'Brian Harman': 88,
    'Daniel Berger': 93,
    'Stephan Jaeger': 98,
    'Brooks Koepka': 129,   // rejoined PGA Tour 2026; ranking fell during LIV years
    'J.T. Poston': 104,
    'Ryo Hisatsune': 109,
    'Kurt Kitayama': 115,
    'Alex Smalley': 120,
    'Emiliano Grillo': 128,
    'Ryan Fox': 134,
    'Gary Woodland': 148,
    'Lucas Glover': 195,
    'Patrick Reed': 210,    // LIV — ranking fell without OWGR events pre-2026
    'Joaquin Niemann': 172, // LIV — confirmed ~#172
    'Cameron Smith': 222,   // LIV — confirmed ~#221-222
    'Brandt Snedeker': 285,
    'Dustin Johnson': 468,  // LIV — confirmed ~#468; PGA invite, no auto qualification
    'Michael Block': 2000,
  },
};